executable    = /afs/cern.ch/work/a/agoetz/public/condorExecutable.sh
arguments    = $(ClusterId) $(ProcId)
output    = /afs/cern.ch/work/a/agoetz/public/output/output.$(ProcId).out
error    = /afs/cern.ch/work/a/agoetz/public/error/error.$(ProcId).err
log    = /afs/cern.ch/work/a/agoetz/public/log/log.$(ProcId).log
RequestCpus    = 4

+JobFlavour    = "longlunch"
transfer_output_files   = ""
queue    100

